version: '3.8'

services:
  kindly-api:
    build: .
    container_name: kindly-api
    restart: unless-stopped
    privileged: true
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - NODE_IP_ADDRESS=192.168.0.50
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"
